version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_PORT: $DB_PORT
  