version: '3.9'

volumes:
  db_data:

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME